# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[character]                         # The name of the module we are configuring is "character"
success_symbol = "[❯](#C5C6D0)"     # The "success_symbol" is set to "❯" with color "#C5C6D0"

[directory]
style = " grey"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
